applications/osmo4_android/jni/wrapper.cpp
modules/droid_audio/droidaudio.c
modules/droid_audio/javaenv.c
modules/droid_audio/javaenv.h

Reverts gpac/gpac#113 (needs further testing)

Revert "Cleanup android audio driver"

---

include/gpac/internal/mpd.h
src/media_tools/dash_client.c
src/media_tools/mpd.c

…string format (patch Damien Merenne)

Fixed m3u8 bugs

---

applications/osmo4_android/src/com/gpac/Osmo4/Preview.java

…pports, set continuous auto focus mode for video recording

Android camera preview

---

modules/ismacryp/isma_ea.c
src/media_tools/text_import.c

@cconcolato Please review because this doesn't apply to WebVTT. Thanks!

Subtitle last empty sample

---

src/utils/color.c

Adding intrinsic conversion : 
- From yuv422 10b to yuv422 8b
- From yuv444 10b to yuv444 8b

add intrinsic conversion

---

modules/dx_hw/copy_pixels.c
modules/dx_hw/dx_2d.c
modules/sdl_out/video.c
src/compositor/compositor_2d.c
src/export.cpp
src/utils/color.c

Tested with X11, Directx and SDL

add support for range extensions formats when opengl mode is disable

---

applications/dashcast/audio_decoder.c
applications/dashcast/audio_muxer.c
applications/dashcast/controler.c
build/xcode/generate_ios.sh
check_revision.sh
mkdmg.sh
modules/aac_in/faad_dec.c
modules/saf_in/saf_in.c
modules/timedtext/timedtext_dec.c
src/media_tools/mpegts.c
src/scenegraph/dom_events.c
src/scenegraph/dom_smjs.c
src/scenegraph/mpeg4_animators.c
src/scenegraph/smil_anim.c
src/terminal/input_sensor.c
src/terminal/media_control.c
src/terminal/media_manager.c
src/terminal/media_memory.c
src/terminal/media_object.c
src/terminal/media_sensor.c
src/terminal/network_service.c
src/terminal/scene.c
src/terminal/terminal.c
src/utils/downloader.c

Remove all non-breaking spaces from code

---

include/gpac/constants.h
modules/vtb_decode/vtb_decode.c
src/compositor/compositor_2d.c
src/compositor/texturing_gl.c
src/compositor/visual_manager_3d_gl.c
src/utils/color.c

see https://github.com/gpac/gpac/commit/939e436cf88cdffd92b94bea7eb1f4a51247187b#commitcomment-19168676

rename 'GF_PIXEL_YPVU' in 'GF_PIXEL_NV12'

---

applications/osmo4_android_studio/app/src/main/java/com/gpac/Osmo4/GpacConfig.java
applications/osmo4_android_studio/app/src/main/java/com/gpac/Osmo4/Osmo4.java

Note :  In this PR we revert this  commit 570873d    temporarily to display the gui

[Osmo4] add support for immersive full-screen mode

---

src/isomedia/box_code_base.c
src/isomedia/box_code_drm.c
src/media_tools/mpegts.c

Fix segfault from fuzzy test vectors

Isom read fixes

---

applications/osmo4_android_studio/app/src/main/AndroidManifest.xml

This commit allows to change the layout (portrait/landscape) without restarting the android application

Fix the detection of orientation change

---

include/gpac/internal/media_dev.h
modules/mediacodec_dec/mediacodec_dec.c
src/media_tools/av_parsers.c
src/terminal/decoder.c

Decoding avc streams ( mp4, ts, dash, hls)
TODO :
- Fix Cropping
- HEVC decoding

Improved mediacodec performances

---

tests/media/ttml/ebu-ttd_sample_invalid_root.ttml
tests/media/ttml/ebu-ttd_sample_mixed_namespaces.ttml

TTML Namespace test was not testing namespace.
Untested: Unsure if those files need to be referenced somewhere else.

Change TTML namespace tests

---

Makefile
generate_installer.bat
tests/make_tests.sh

some small changes I had to make to scripts while setting up the new version of buildbot

Buildbot fixes

---

applications/mp4box/fileimport.c
applications/mp4box/main.c
src/isomedia/box_code_base.c
src/isomedia/isom_read.c
src/isomedia/isom_write.c

* import/dump/display unknown boxes by their original 4cc
* allow dumping of known boxes too

udta boxes

---

src/media_tools/av_parsers.c
src/media_tools/media_import.c

fix emulation bytes and par writing in hevc sps

fix? for #820

---

tests/scripts/dash-live-generation.sh
tests/scripts/dash-main-singlefile.sh
tests/scripts/dash-main.sh
tests/scripts/dash-media-input-dur.sh
tests/scripts/dash-subtitle.sh
tests/scripts/dash-template.sh
tests/scripts/dash-timeline.sh

Line coverage: 67 % -> 72 %
Function coverage: 86.8 % -> 93.4 %

Dasher test coverage improvements

---

src/media_tools/dash_segmenter.c

minor fixes to ensure hashes constitency between master and PR#784

Fix for hashes

---

src/media_tools/text_import.c

if a subtitle start & end on the same second, Gpac won't wrap.
So these commits will fix that based on a comparison including frame precision.

Fix "short" subtitling duration

---

applications/mp4box/filedump.c
applications/mp4box/fileimport.c
applications/mp4box/main.c
include/gpac/isomedia.h
include/gpac/media_tools.h
modules/isom_in/load.c
modules/isom_in/read.c
modules/isom_in/read_ch.c
src/ietf/rtp_streamer.c
src/isomedia/avc_ext.c
src/isomedia/box_code_base.c
src/isomedia/isom_read.c
src/isomedia/isom_write.c
src/isomedia/sample_descs.c
src/isomedia/track.c
src/media_tools/dash_segmenter.c
src/media_tools/filestreamer.c
src/media_tools/isom_hinter.c
src/media_tools/isom_tools.c
src/media_tools/media_export.c
src/media_tools/media_import.c
src/media_tools/mpd.c
src/media_tools/text_import.c
src/scene_manager/loader_qt.c

Should this be done also for 'pict'?

Add support for the new track handler type 'auxv'

---

include/gpac/avparse.h
include/gpac/internal/isomedia_dev.h
src/isomedia/avc_ext.c
src/isomedia/box_dump.c
src/isomedia/box_funcs.c
src/media_tools/av_parsers.c

- add Tile List OBU
- fix metadata types, and add ITU T-35
- fix av1C as a FullBox
- fix XML dump
- fix uninitialized variable

Various AV1 fixes

---

src/media_tools/ismacryp.c

Passing a Constant IV that had the wrong size (e.g. 15 vs 16) was not logged as an error and MP4Box was silently encrypting with an IV of 0. 
Also, in general I think many warning messages should be error messages, so that the `-strict-error` flag can actually be used.

Add more logs to CBCS encryption and turn warnings into error messages

---

src/isomedia/track.c

Change-Id: Iacc803a654935940c76a8a9de34a316102ae166e

Fix incorrect variable check order in NewMedia function

---

src/media_tools/text_import.c

Fix TTML div text node warning

---

applications/mp4box/main.c
include/gpac/media_tools.h
src/isomedia/movie_fragments.c
src/media_tools/dash_segmenter.c
src/media_tools/media_export.c
src/utils/os_file.c

I'm trying to avoid diffs between both branches for existing users.
Missing:

Filters master diffs

---

applications/mp4box/filedump.c
src/isomedia/drm_sample.c
src/isomedia/isom_read.c

follows up https://github.com/gpac/gpac/commit/e78dbcddcf16041863fc1bfc0865a6c5cebffb90
@jeanlf is this approach ok for you?

improve NALU dump on encrypted data

---

applications/mp4box/main.c
include/gpac/internal/isomedia_dev.h
include/gpac/isomedia.h
src/export.cpp
src/isomedia/box_code_meta.c
src/isomedia/meta.c

initial support, maybe would need to be generalized to items. Also id spaces should be updated at track level or in "unif" case.

add support for entity groups in image items

---

src/media_tools/av_parsers.c

Should also be ported to master

set matrix coefficients in VP9 imports

---

applications/gpac/main.c

```gpac``` cannot e stopped with a signal at the moment.

catch SIGTERM to be able to exit without any user interaction from a script

---

include/gpac/dash.h
src/export.cpp
src/filters/dmx_dash.c
src/media_tools/dash_client.c

I was not 100% sure of the location of the code.

dash client: consider SuggestedPresentationDelay

---

applications/mp4box/fileimport.c

It's a valid configuration for profile 8.

mp4box/fileimport: Allow profile 8.4 Dolby Vision config

---

applications/mp4box/fileimport.c

This PR adds support for the -mfra option when splitting with mp4box.

-mfra option in mp4box split

---

configure

fix build on aarch64, missing fPIC

Update configure, aarch64 build

---

applications/mp4box/filedump.c

If you use both -dnal track_id and -std on a AV1 input file, you will always receive an error "Track #1 is not NALU or OBU based!", even though the track *is* OBU based.
This is because the check for the ISOM media subtype is erroneously skipped when dumping to stdout.
Fix it by doing the ISOM media subtype check earlier.

fix using both -dnal and -std on AV1 input

---

src/filters/out_route.c

I made some changes and cleanup to ATSC related parameters

Changes and cleanup to ATSC 3.0 related parameters in out_route.c

---

include/gpac/constants.h
src/isomedia/box_dump.c

Not sure about that "KeyBlack" name. Obviously feel free to edit.

uncC: minor FDIS cleanups

---

src/evg/ftgrays.c
src/evg/raster_yuv.c
src/evg/stencil.c
src/utils/math.c
src/utils/path2d.c

fix failure and warning on GPAC_FIXED_POINT

---

src/filter_core/filter_pid.c
src/filters/ff_enc.c
src/filters/inspect.c
src/media_tools/dash_client.c
src/media_tools/mpd.c
src/scenegraph/svg_attributes.c
src/utils/os_config_init.c
src/utils/os_file.c
src/utils/os_net.c

- Replace `strchr` with `strpbrk` where applicable.
- Some fixes

Replace strchr by strpbrk + some fixes

---

src/filters/out_route.c

The inclusion of the `nozip` option provides the capability for the `routeout` filter to refrain from compressing the manifest.

Add nozip option to routeout filter

---

share/emscripten/gpac.html
src/utils/error.c

This PR imrproves the console experience by these changes:
- Taller console
- ANSI color codes shown properly
- Some useful shortcuts
- `Ctrl+C`: Clear current command
- `Ctrl+L`: Clear console
- `Ctrl+A`: Move cursor to beginning of command
- `Ctrl+E`: Move cursor to end of command

Improved console experience in gpac wasm demo page

---

src/isomedia/isom_read.c
src/media_tools/route_dmx.c

Some minor changes:
- typo
- Fix display inconsistency: Update printf format specifiers for consistency.
- Update comment

Refactor comments and improve display consistency

---

include/gpac/route.h
src/filters/out_route.c

This one should be quite consensual CC @soheibthriber @jeanlf @touatily

Buildbot mabr misc

---

src/isomedia/box_dump.c
src/isomedia/box_funcs.c

decode uncompressed codec item timestamps

---

src/isomedia/box_dump.c

Typo fixes split out from #2908

fix typos in 23001-17 box dump

---

src/filters/dasher.c

Fix Possible Memory Leak in `dasher`

---

src/media_tools/dash_client.c

I changed the static declaration of szTemplate char pointer to a dynamic declaration.

fix possible overflow in dash_client 

---

src/isomedia/box_dump.c
src/isomedia/box_funcs.c

From 23001-17 draft AMD2.
Also includes some minor typo fixes I noted while reading. I'll split those out if you'd prefer.

uncompressed: add icbr and cmpC box dump

---

include/tests.h
src/Makefile
unittests/README.md

fixes #2961 building unit tests : `./configure --unittests && make`

fix unittests build

---

src/filters/dasher.c
src/filters/ff_enc.c
src/filters/reframe_nalu.c

There are 3 distincts commits in this PR that could be cherry-picked if the PR is not acceptable.

dasher shouldn't anticipate segment boundary on video

---

applications/gpac/gpac_help.c
src/filters/compose.c
src/utils/os_config_init.c

- added missing line after code blocks
- added tagging of options by level
- prevent collapse on all options

Fixes for genmd+mkdocs

---

include/gpac/tools.h
src/filters/in_route.c
src/filters/in_route.h
src/filters/in_route_repair.c
src/utils/downloader.c
src/utils/error.c

This PR introduces two key improvements:
1. Multiple Repair URLs Support
2. Handling Servers Without Range Support

Add support for multiple repair URLs and handle servers without range support

---

src/filters/reframer.c
src/filters/rewrite_nalu.c

- [fix segfault when no DSI is encountered so far](https://github.com/gpac/gpac/commit/7649ae723adc4f0320fb1f9528c02adec1374c75)
- [fix cts by adding track delay](https://github.com/gpac/gpac/commit/0f2ba3b7164dd35418f20f53ec5fa69da626e648)

Reframer Fixes

---

src/media_tools/route_dmx.c

mabr client: fix segment timeline regression

---

include/gpac/internal/media_dev.h
include/gpac/tools.h
src/filter_core/filter_props.c
src/filters/inspect.c
src/filters/reframe_nalu.c
src/filters/reframer.c
src/media_tools/av_parsers.c
src/utils/constants.c

fixes #3080
```bash
gpac -i input.ts rfnalu @ inspect:deep:fmt="\$cts\$ -> \$tmcd\$\$lf\$"
```

Add timecode formatting and structure updates

---

src/filters/dasher.c

Delete old fragments in SSR mode

---

src/filters/bsrw.c

This PR enables the `bsrw` to put timecode based on UTC time. It will use the following sources for the UTC time, in priority order:
- `GF_PROP_PCK_SENDER_NTP`
- `GF_PROP_PCK_UTC_TIME`
- Current UTC time

add new `tc=utc` option to `bsrw`

---

src/filters/write_tx3g.c

Trying to solve #3229. Is there anything else we may want to add here?

ttml: reference default region in body

---

include/gpac/isomedia.h
include/gpac/sync_layer.h
src/filters/encrypt_cenc_isma.c
src/filters/ff_enc.c
src/isomedia/isom_write.c

QT: meta atom is not a full box

---

include/gpac/filters.h

Recently, I tried to compile an example application that inputs and outputs data using GPAC in C++. The only compatibility issue I observed was with named designators.

Compatibility with C++14

---

include/gpac/internal/media_dev.h
src/filters/load_text.c
src/media_tools/webvtt.c

detected by valgrind as a use-after-free

fix vtt in file aliasing issue
