src/media_tools/dash_segmenter.c

The DASH-AVC/264 settings contain an invalid profile ("`guildelines`" vs. "`guidelines`"). This causes it to not be compliant to the spec.

Fix typo in DASH-AVC/264 profiles.

---

include/gpac/module.h
src/utils/module.c

When using GPAC as a static library, provide an easy way for the user to
choose which modules to load without having to change GPAC source code.

Allow customization of static module loading.

---

modules/droid_out/droid_vout.c

In the Android video out driver, glDisable is called at init and then
for each rendering step. As per the glEnable man pages, the capability
flags that are disabled in the driver are disabled by default:
The initial value for each capability with the exception of
GL_DITHER and GL_MULTISAMPLE is GL_FALSE.
So there is no need to call glDisable for those. Besides, it causes
spurious log messages on some Android devices:
W/Adreno-ES20(24368): <process_gl_state_enables:519>: GL_INVALID_ENUM
which slows down the rendering process.

[Android] Do not call glDisable when it is not needed.

---

include/gpac/internal/m3u8.h
include/gpac/internal/mpd.h
include/gpac/modules/service.h
src/media_tools/dash_client.c
src/media_tools/m3u8.c
src/media_tools/mpd.c
src/media_tools/mpegts.c

Here is an ugly try at HLS decryption, but it might help to see what needs to be done in order to implement it.
The first part is adding key and iv extraction in the m3u8 code. It is not complete as the IV attribute is not extracted but I did not encounter a file with that attribute as of now so the IV is always the media sequence number.
Next I added code to export the key and iv in the mpd representation and code to the mpd parser to extract them. 
Finally I added code in the dash client to decrypt the downloaded segments. The decryption is done by the drm_decrypt function. It uses a proprietary solution which fetches the key using some SSL client certificate and do the decryption. It could be easily replaced by another one implementing the hls aes "standard" cbc 128 decryption.
It's …

HLS decryption

---

src/media_tools/dash_client.c

When closing the dash thread, make sure that it is stopped by checking
for GF_DASH_STAE_STOPPED. Checking for not GF_DASH_STATE_RUNNING is not
sufficient if the thread is being stopped before the main loop of the
thread.
This might be related to issue #110 but there are also other problem in there.
I also removed the reset of dash->mpd_stop_request in the thread as it creates a race condition if the thread is closed before it.

Fix dash cleanup path.

---

include/gpac/internal/isomedia_dev.h
src/isomedia/isom_write.c

I think that we need unpack also CompositionOffsetBox before editing/removing the entries (cf. #147 )

fix bug in ctts unpack mode when removing sample

---

README.md

- This will display an image showing the current build status of the
master branch. To make this work according to
http://docs.travis-ci.com/user/status-images/ I had to change the
README's file extension from plain text to Markdown. I've not
touched anything else to make it more Markdown-like, though.
- This fixes #117 and was found through http://issuehub.io/.

Add a Travis CI build status image to the README

---

configure

The configure script seems to be compatible with Macports which installs
its stuff into /opt/local.
However, Homebrew doesn't have the same behavior. It installs its stuff
into a Cellar folder, then, links it into /usr/local/{include,lib,bin}.
However, for example, the png detection uses -Iprefix/include (line
1225), but this include path is not used afterwards.
So, if you have installed libpng with Homebrew, configure detects a
"system" png, but fails to compile since $prefix/include isn't used as
include path at compile time.

Make configure script compatible with Homebrew on MacOS

---

applications/mp4box/main.c
include/gpac/media_tools.h
src/export.cpp
src/media_tools/dash_segmenter.c

DASH-IF IOP 3.1 says in 7.5.2 that:
> ContentProtection Descriptors SHALL always be present in the AdaptationSet element, and apply to all contained Representations
The same is related to previous IOP versions. ContentProtection was never allowed to be in Representation.

DASH-IF IOP profiles require ContentProtection only in AdaptationSet.

---

applications/mp4box/main.c
applications/mp4client/main.c
include/gpac/utf.h

In 108b820(master, 2016/2/19) nightly build binary.
```
> mp4box.exe -info 日本語漢字.mp4
Length allocated for conversion of wide char to UTF-8 not sufficient
```
many cjk charactors encoded to three bytes in utf8 encoding.
But current implementation, allocate 2 * len bytes.
[RFC3629: UTF-8, a transformation format of ISO 10646](https://tools.ietf.org/html/rfc3629) defines UTF8 max octet sequence size is 4.
This patch fixed utf8 memory size calculation.

Fixed UTF8 memory size calculation

---

configure

The `--cc` configure argument doesn't work on Darwin (OS X) because the configure script overwrites the value of `cc` later. This PR fixes that bug by not overwriting `cc`.

Don't override $cc on Darwin

---

src/utils/error.c

By playing with the ANSI color codes and prepending the color code before the log message, I add some red to the errors and yellow to the warnings.

Colorizing the log of libgpac #14

---

static.mak

I was getting build errors with this commandline:
```
bash ./configure --cpu=i686 --enable-static-bin --static-mp4box --extra-cflags='-m32' --extra-ldflags=-s
```

Fix compilation with `CONFIG_DIRECTX=yes`.

---

src/utils/os_divers.c

Uses sysconf() to get processor core count. Existing FreeBSD-specific code results in build errors in FreeBSD 10.1.

Fixes build error in FreeBSD

---

applications/mp4box/main.c

The help text for #audio is mistakenly the same as for #video.

Fix a typo in Dash help

---

applications/mp4box/main.c
include/gpac/ismacryp.h
src/media_tools/ismacryp.c

When merged, I need to modify http://gpac.io/mp4box/encryption/common-encryption/

fix IsEncrypted in CENC xml: write only the PSSH

---

configure

The referenced commit broke compilations when both /mingw32 and
/mingw64 paths exist and people tried to compile 32-bit.

Fix broken compilations with MSYS MinGW since 5b14f8328

---

include/gpac/configuration.h
src/utils/os_thread.c

configuration.h should check for _WIN32, not the GPAC defined WIN32. …
…Otherwise external applications using GPAC also have to define WIN32.

Win32 config h define

---

include/gpac/base_coding.h
include/gpac/internal/isomedia_dev.h
include/gpac/isomedia.h
include/gpac/version.h
src/export.cpp
src/isomedia/box_code_base.c
src/isomedia/box_dump.c
src/isomedia/box_funcs.c
src/isomedia/isom_write.c
src/isomedia/movie_fragments.c
src/media_tools/isom_tools.c
src/utils/base_encoding.c

- add full tfxd support
- add mss manifest box (invented 'mssm' name)
- constify api (gf_base64_encode()) => bump minor api

microsoft smooth streaming mux missing boxes

---

src/isomedia/track.c

the memory allocation failure was checked one line too late

check out-of-mem before assigning member

---

applications/mp4box/main.c
tests/scripts/dash.sh

This commit improves the test coverage for the Dash Segmenter (src/media_tools/dash_segmenter.c).
Line coverage goes from 33.1% to 43.5%
Function coverage goes from 59.7 % to 66.7 %

Enlarge test coverage for dash segmenter

---

modules/mediacodec_dec/mediacodec_dec.c

This commit fixes the crash in https://android.googlesource.com/platform/frameworks/av/+/0c3be87/media/ndk/NdkMediaCodec.cpp#104 when we pass NULL pointer to AMediaCodec_delete

Fix crash in mediacodec

---

tests/scripts/dash.sh

This commit enhance code coverage in dash segmenter:
Line coverage goes from 43.5 % to 58.7 %
Function coverage goes from 66.7 % to 84.7 %

Add test for mpeg-ts dash

---

tests/scripts/dash-live.sh
tests/scripts/dash-ts.sh
tests/scripts/dash.sh

This commit splits the previous dash tests in several files and use files with regular GoP.
The dash-live test is also more accurate (using a forked process).
The following tests are ok on my debian machine:
./make_test.sh -v scripts/dash.sh
./make_test.sh -v scripts/dash-live.sh
./make_test.sh -v scripts/dash-ts.sh

Tests improvement

---

applications/osmo4_android_studio/app/src/main/java/com/gpac/Osmo4/Osmo4.java
applications/osmo4_android_studio/app/src/main/java/com/gpac/Osmo4/Osmo4GLSurfaceView.java
include/gpac/options.h
src/compositor/navigate.c
src/terminal/terminal.c

- On the touch event hide the android menu first if it is visible, otherwise hide/show the GUI.
- Disable 360 mouse/touch navigation if orientation sensors are enabled.
- Make content (Video and GUI) appear above the navigation bar.

[Osmo4] Some improvement on the Android menu and 360 navigation

---

modules/droid_audio/droidaudio.c

This commit fixes crash when we enable debug mode

[Android] No need to fill audio buffer in a critical region

---

applications/mp4box/main.c
include/gpac/tools.h
src/export.cpp
src/media_tools/media_export.c
src/utils/os_file.c
tests/make_tests.sh

at several places in the code, when checking for a file extension, we only do something like `strrchr(outfile, '.');`
however this doesn't work with a full path that contains directory names with a dot and a file without it
e.g.: 
`mp4box -logs all@debug -raws 1 test.extension\noext`
will write to the wrong path
and
`mp4box -logs all@debug -raws 1 test.extension\meta-metx.mp4`
will fail when trying to check the extension for `test.extension\meta-metx_track1`
I added a `gf_file_ext_start()` function to get the extension while taking the path into account, and fixed the 2 cases above. There are other places that can use this function that I haven't tested yet.

fix some bugs with file/path extensions

---

applications/mp4client/extract.c

another case where it's better to use the new `gf_file_ext_start()` function instead of `strrchr(path, '.')` to find a file extension in a path

fixed extension searching on avi export in mp4client

---

src/media_tools/dash_segmenter.c
tests/scripts/dash-ts.sh

This PR increases the code coverage by testing relative path in segment name and testing singlefile mode in MPEGTS Dashing.
Moreover, it seems to fix the issue #736.

Fixmpegtsdash

---

src/odf/odf_dump.c
src/utils/url.c

This PR does some dusting in the handling of relative paths. 
Most notably, it fixes the following scenario: 
the test file `tests/media/bifs/bifs-2D-background-background2D-movie.bt` contains 
```
muxInfo MuxInfo {
fileName "../auxiliary_files/enst_video.h264"
}
```
if we export it to xmt with 
`mp4box -xmt media/bifs/bifs-2D-background-background2D-movie.bt`
it will wrongly try to "resolve" the relative path, resulting in 
`        <StreamSource url="media/auxiliary_files/enst_video.h264" >`
After that, doing
` MP4Box -mp4 media/bifs/bifs-2D-background-background2D-movie.xmt`
will fail because it's trying to open `media/bifs/media/auxiliary_files/enst_video.h264` instead of  `media/auxiliary_files/enst_video.h264`
With this PR, the same command outputs: 
`        <StreamSource …

Fix relative paths

---

build/xcode/generate_ios.sh
build/xcode/gpac4ios.xcodeproj/xcshareddata/xcschemes/libgpac_static.xcscheme
build/xcode/gpac4ios.xcodeproj/xcshareddata/xcschemes/osmo4ios.xcscheme
modules/droid_mpegv/droid_mpegv.c

two things I came across while rebuilding the project on new machines: 
android: a return type warning seem to give an error (Werror is probably defined somewhere)
ios: when ran for the first time, the xcodebuild archive command complains that no schemes exists in the project
schemes can be auto-generated in the xcode gui, but for the project to be buildable from scratch from the command line, it's better to include the schemes in the repo

small things for mobile builds

---

src/scene_manager/scene_dump.c

the test file `tests/media/bifs/bifs-2D-interactivity-mousesensor.bt` contains a script block with a `url` element containing some javascript 
if we export it to xmt the script contents is copied properly, however if we export that xmt back to bt, the script content has disappeared and the url element is empty
_this happens on linux only, it works on both windows and macos_
when trying to dump the content of the `url` element, we first try to convert it to UTF16 and write it, one wide-character at a time, with `fputwc()`
however, the standard says that a `FILE*` stream can be either:
- _byte-oriented_: when using functions such as `fprintf`, `fputc`, etc.
- _wide-oriented_: when using functions such as `fwprintf`, `fputwc`, etc. 
once its orientation is set, either by the first i/o …

invalid use of fputwc on already non-wide stream

---

src/scene_manager/swf_parse.c

when trying to run the following test
`MP4Box -add tests/media/xmlin4/anim.swf:fmt=svg -new ./results/temp/text-stxt-svg.mp4`
on linux, we get 
```
SWF import (as text - type: svg)
SWF Import - Scene Size 0x0 - 0 frames @ 0 FPS
```
and nothing is done - on windows we rightly get 
```
SWF import (as text - type: svg)
SWF Import - Scene Size 170x170 - 30 frames @ 25 FPS
```
the problem comes from the call to zlib for unpacking a compressed swf : 
we read the length of the data on 4 bytes (`u32`) in `dst_size`, and (weirdly) zlib expects a `uLongf*` as its size argument (`uLongf` being 8 bytes long)
passing `(uLongf *)&dst_size` is incorrect because the extra bytes aren't necessarily initialized to 0 so the numeric value becomes garbage
by copying the `u32` to a `uLongf` first and then …

invalid cast in swf parser decompress

---

applications/osmo4_android_studio/app/src/main/java/com/gpac/Osmo4/GPACInstance.java
build/android/jni/modules/gm_mediacodec_dec.mk
include/gpac/maths.h
include/gpac/modules/codec.h
modules/mediacodec_dec/Makefile
modules/mediacodec_dec/mediacodec_dec.c
modules/mediacodec_dec/mediacodec_dec.h
modules/mediacodec_dec/mediacodec_dec_jni.c
modules/vtb_decode/vtb_decode.c
shaders/fragment.glsl
src/compositor/texturing_gl.c
src/compositor/visual_manager.h
src/compositor/visual_manager_3d_gl.c

Comparison between surface mode and buffer mode :
stream : UHD AVC (3840 x 2160), 50fps, duration 55s
device : HTC 10 
Android version : 6.0.1
Stats : 
- Surface  mode (zerocopy)                                                                     
FPS : ~50                                    
CPU: 50%
decoding time of a frame : ~5 ms
- Buffer mode : 
FPS : ~20
CPU : 68%
decoding time of a frame : ~30 ms + push time ( 24 ms)

[Android] zerocopy mediacodec

---

tests/scripts/dash-if-live.sh
tests/scripts/dash-if-ondemand.sh
tests/scripts/dash-live-generation.sh
tests/scripts/dash-live.sh
tests/scripts/dash.sh

This PR is splitting dash tests in 5 tests cases:
dash.sh: Using Dash OnDemand profile
dash-live.sh: Using Dash Live profile
dash-live-generation.sh: live DASH session (with Dash Live profile)
dash-if-ondemand.sh: Using Dash-if on demand profile
dash-if-live.sh: Using dash-if live profile
The previous tests were producing adaptation sets with multiplexed media streams. Considering the rare usage, tests are now producing adaptation sets with non multiplexed media streams.

Split Dash tests cases

---

.gitattributes
applications/mp4client/main.c
build/msvc10/gpac.sln
build/msvc14/gpac.sln
include/gpac/mpegts.h
include/gpac/setup.h
include/gpac/tools.h
src/export.cpp
src/isomedia/track.c
src/media_tools/av_parsers.c
src/media_tools/m2ts_mux.c
src/media_tools/media_export.c
src/utils/os_file.c
tests/make_tests.sh
tests/media/xmlin4/first.xml
tests/media/xmlin4/last.xml
tests/media/xmlin4/meta-mett.nhml
tests/media/xmlin4/second.xml
tests/media/xmlin4/text-stxt.nhml
tests/scripts/mp42ts.sh
tests/scripts/smooth.sh
tests/scripts/xmlin.sh

Hash references (up to date for non playback tests) are available here : 
http://download.tsi.telecom-paristech.fr/gpac/gpac_test_suite/resources/hash_refs
use `./make_tests.sh -sync-hash`  to get them
A few tests are still not hashable across all platforms.

fixes for using hash verification in test suite

---

src/media_tools/ismacryp.c

I had an issue with a file containing the following sample data:
```
00 00 00 02 09 50 
00 00 00 09 06 01 05 00 2c 00 00 10 80 
00 00 00 00 
00 00 00 02 0c 80 
00 00 00 02 09 50 
00 00 00 09 06 01 05 00 30 00 08 10 80 
00 00 00 0d 06 04 09 b5 00 31 44 54 47 31 41 f8 80 
00 00 02 0d 01 9e 0e 2d e4 67 f8 0a 5e 45 fe 31 5c 2e 58 8c 48 49 b1 14 a1 d6 b0 06 e9 2f a8 90 14 dc 7f d1 55 90 d2 d3 33 5a 60 9c 91 4f 1c 96 94 fa 72 4e da 8b d6 14 eb b4 c5 ef 61 64 c4 d1 8c cd f7 9d 26 1d fc 13 62 8e 66 9d af 96 a0 e4 e1 34 8f ec c8 23 4b 7b 62 ce 74 43 5f aa d2 0d e6 38 22 47 e7 a0 15 99 be 1e df a3 45 28 e4 5c 98 d3 25 fe dd 03 28 ce 76 f6 ae eb 05 e3 f4 c5 5f 4d 77 5d e2 8c 9f bf c7 48 da 55 7d 11 30 40 27 4d c6 50 bf 59 f2 0a 29 77 5b 91 6b 52 7e 3d d6 1b 0a 44 1c a2 0b 0a 25 c1 0c 29 98 e3 82 bd …
```

Don't read NALU type if NALU size is 0

---

applications/mp4client/main.c

linked to #843 : 
* added GPACVersion in the General section on GPAC.cfg
* when running mp4client, if GPACVersion is different from the current version, we rebuild the plugins cache
this will avoid failing because of changes in interfaces names

cfgfile: rebuild plugins cache when running a new version

---

src/isomedia/meta.c
src/media_tools/isom_hinter.c

2 bugfixes: 
* on -hint using a GF_Fraction for the time scale change prevents rounding errors 
* on -set-xml, the length of an xml box is calculated by strlen so we have to add a \0 after reading from file otherwise it overflows

small fixes

---

applications/mp4box/main.c
include/gpac/media_tools.h
src/media_tools/dash_segmenter.c

This PR adds an option to disable cache for dasher inputs. 
It fixes issue #835 
One can now use the following command with growing file:
MP3Box -dash-live 2000 -subdur 1000 /tmp/growingfile.mp4

Enablegrowingfiledashing

---

src/media_tools/dash_segmenter.c
tests/make_tests.sh
tests/scripts/dash-descriptor.sh

running the tests with --enable-mem-track revealed two leaks in dash_segmenter that should be fixed by this PR
(also in this, small changes on test scripts)

fix 2 memory leaks in dash_segmenter

---

applications/mp4box/main.c
src/utils/os_file.c

I see there are some commits which introduce wide char handling on Win32.
It's very helpful for CJK language users.
But I think some code are incorrect.
"char*" in Windows API / C runtime on Windows often refers to string in local 
encoding, not UTF8 string. Using wmain on Windows to receive wide char 
argument is a good idea, but it's not lossless to convert wide char string to 
local string.
I modified the code to convert argument string to utf8 on Windows,
and it uses utf8 in internal program logic, and wide char string for file api 
on Windows.
Note: 
If console code page is not set to utf8, the output log will still be mojibake.

Use widechar crt/api on Win32

---

src/isomedia/box_dump.c

Hi,
I noticed that `tenc` box writes _key id_ value instead of _IV_ when doing `MP4Box -diso`. This is caused by a typo or copy-paste error that my pull request fixes.
Cheers, Tijn

Typo in tenc_dump()

---

src/media_tools/media_import.c

Simple fix. When importing an NHML with a Sample with mediaFile and that file was missing, the file not found message was not the right one.

fix wrong log message

---

configure

As of freetype-2.9.1 the freetype-config file no longer gets installed
by default.
See also [Make installation of `freetype-config' optional](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=a7833f26c4ac45cafe1dffdcd7f7dcfd6493161c) commit by freetype upstream.

Use pkg-config to find freetype

---

applications/mp4box/main.c
include/gpac/media_tools.h
src/media_tools/dash_segmenter.c

Useful when muxed segmented streams are processed separately by the client (e.g. like two independent CMAF tracks sharing only the moov)

add segmentation option to insert a tfdt per traf

---

include/gpac/internal/isomedia_dev.h
src/isomedia/box_code_base.c
src/isomedia/isom_intern.c
src/isomedia/isom_read.c
src/media_tools/isom_tools.c

mfra is created according to ISO/IEC 14496-12:2015(E)
part 8.8.9 Movie Fragment Random Access Box
Presence of this box speeds up seeking over fragmented file
It also fixes some issues on mfra write out (eg missed writing box header, etc)
Debugging/testing were done @win32 using msvc compiler on gpac_mp4box_mini solution.
As a proposal maybe it makes sense to add new cmd line option for this mfra box? (say "-mfra)

Added composing of the mfra box when producing fragmented mp4.

---

applications/mp4box/main.c
include/gpac/isomedia.h
src/isomedia/box_dump.c
src/isomedia/iff.c
src/isomedia/meta.c

This pull request closes issue #1080. It adds a command-line option to MP4Box (`icc_path`) to add an ICC color profile when writing a HEIF file. Also, when reading a HEIF file with an ICC color profile, it adds it (base64 encoded) to the IsoMedia XML dump.
This change is needed to correctly read and write HEIF images with a non-sRGB color profile, for example HEIF images created by iOS devices (which use the wider gamut P3 color profile).

ICC color profile support for HEIF

---

src/isomedia/movie_fragments.c

TrackExtensionPropertiesBox seems only needed when CompositionToDecode is used. This PR only creates the TrackExtensionPropertiesBox when needed.

only insert trep when needed

---

applications/mp4box/main.c
include/gpac/media_tools.h
src/media_tools/dash_segmenter.c

"-segment-ext" is currently ignored for initialization segments (and bitstream switching segments, and index segments). This PR adds "-init-segment-ext" to fix that.

Add option to MP4Box to set initialization segment extension

---

applications/mp4box/main.c
include/gpac/internal/isomedia_dev.h
include/gpac/isomedia.h
include/gpac/media_tools.h
src/isomedia/box_code_base.c
src/isomedia/isom_write.c
src/media_tools/dash_segmenter.c

Some devices seem to have a problem when `mvex` is provided before `trak`. Also Table 3 in CMAF places `mvex` after, although order of boxes is not mandated in CMAF.

add -mvex-after-traks option to MP4Box when dashing

---

include/gpac/internal/mpd.h
src/media_tools/dash_segmenter.c

The current code which uses the `memmove` approach does not seem to work. Running a simple test (based on https://github.com/gpac/gpac/blob/master/tests/scripts/dash_cues.sh) in debug mode triggers an assert https://github.com/gpac/gpac/blob/master/src/isomedia/movie_fragments.c#L1520: 
```
Assertion failed: (movie->root_sidx_index == movie->root_sidx->nb_refs), function gf_isom_close_segment, file gpac/src/isomedia/movie_fragments.c, line 1520.
```
Also if run in non-debug mode, this generates an invalid `sidx`, with as many entries as cues but with only the first entry having non-zero values.
In this PR, the cues are not memmoved, each cue is marked if processed. The simulation pass and the normal pass both work with the same number of cues.

fix bug in dash-cue option

---

include/gpac/internal/isomedia_dev.h
src/isomedia/movie_fragments.c
src/media_tools/dash_segmenter.c

Files generated today with -no-frag-defaults do not pass CMAF validation checks. These changes fix that problem. Could be also behind another flag if -no-frag-defaults is really used.

fix use of -no-frag-defaults

---

doc/man/mp4box.1

The `-delay` parameter does not accept any "LAN" (it accepts time in milliseconds).
The incorrect description was probably caused by a copy&paste from the `-lang` parameter:
```
-lang [tkID=]LAN
sets the language of all tracks or the given track. LAN is the ISO 639-2 3 character code.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-delay [tkID=]delay_ms
sets the delay in milliseconds of all tracks or the given track. LAN is the ISO 639-2 3 character code.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Fix the description of -delay for MP4Box in its man pages

---

src/isomedia/box_dump.c

In 'cbcs' case, the IV is constant and not provided per sample. Current `-diso` produces lots of `IV="0x"` attributes.

do not dump 'IV=0x' when IV size is 0

---

applications/mp4box/fileimport.c
applications/mp4box/main.c
include/gpac/media_tools.h
src/media_tools/media_import.c

For AAC or HE-AAC it may be interesting to signal how much pre-roll is needed, as documented for example in [Apple documentation](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFAppenG/QTFFAppenG.html)

adding support for audio_roll

---

applications/mp4box/main.c
include/gpac/isomedia.h
src/isomedia/meta.c

and fix parsing of single keyword options: If the file was called "alpha.obu" the strnicmp was matching it.

add support for tagging image item as alpha

---

applications/mp4box/fileimport.c
include/gpac/internal/isomedia_dev.h
include/gpac/isomedia.h
include/gpac/media_tools.h
src/isomedia/box_code_base.c
src/isomedia/box_dump.c
src/isomedia/box_funcs.c
src/isomedia/iff.c
src/isomedia/isom_write.c
src/isomedia/meta.c
src/media_tools/media_import.c

Few comments about this PR:
- it enables addressing comments in https://github.com/AOMediaCodec/av1-avif/pull/50
- it adds support for the `pixi` box for all image items
- it adds the `auxi` box when the `alpha` import string is given. Meant to be used as in `-add file.obu:hdlr=auxv:alpha`.  
- it fixes a bug with writing of `auxC`
- the `meta_find_prop` seems buggy. It searches for a property that as the same value as the given in the `searchprop` field but `searchprop` is initialized to 0 which might be a value for which a property is searched... I did not fix that here.
- We've reached the end of `GF_MediaImporter flags` space (32 flags defined). I had to use a separate field `is_alpha`. Some harmonization may be needed here or at least some guidance on when to use flags and when to …

Improved HEIF/MIAF/AVIF support

---

src/isomedia/box_dump.c

This PR fixes one problem: when the initialization vector starts with 0, no PIFFSampleEncryptionEntry was dumped because of the use of strlen.
The PR also harmonizes the dump between the PIFF senc box and the senc box (adding sample number in dump). Ideally the code should not be duplicated.

Piff senc dump fix

---

Makefile

The [strip command provided with macOS](https://www.unix.com/man-page/osx/1/strip/) does not have a `-g` option, but does have `-S` which is also recognized by [GNU](https://linux.die.net/man/1/strip) and [BSD](https://www.freebsd.org/cgi/man.cgi?query=strip&sektion=1&manpath=freebsd-release-ports) strip.
So 8256a66ae5c17dff965c67cf14a03fa106448925 introduced the following error during installation of non-debug builds using Apple's strip:
```
make installdylib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: unrecognized option: -g
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip [-AnuSXx] [-] [-d filename] [-s filename] [-R filename] [-o output] file [...]
make[1]: *** [installdylib] …
```

Strip with '-S' instead of '-g' to fix macOS installation

---

applications/mp4box/filedump.c
src/media_tools/media_import.c

I did the following test:
MP4Box -add file.obu:deps file_deps.mp4
MP4Box -add file_deps.mp4:refs file_deps_refs.mp4
I played the final file with VLC and did not see any issue.
For review. More tests to be done. Do not merge now.

mark AV1 frames with refresh_frame_flags = 0 as disposable

---

src/isomedia/isom_write.c

because it would lead to isobmff files that aren't parsed correctly, see [debug.zip](https://github.com/gpac/gpac/files/3076094/debug.zip)
we could probably be able to provide more relevant error messages, could someone have a look?

check sample description entry type (either UUID or codec_tag) are not NULL

---

src/media_tools/text_import.c

If a namespace error occurs, so far the `body` node was always blamed for it, which is fixed by this commit.

Fix EBU-TT-D namespace error location

---

src/media_tools/isom_tools.c

This issue only arises on v0.8 (not on v0.9).
Diff: I've just added a 'if'.
I think we should also generate test reference content for the 'par' parameters.

don't rewrite sps when par_num is -2 (i.e. untouched)

---

applications/mp4box/fileimport.c

- the duplicate doesn't exist on the filters branch, which served as a guideline for this fix
- some errors could be overwritten, they are now managed.

Removing duplicates in fileimport.c in MP4Box

---

src/isomedia/box_code_base.c
src/utils/bitstream.c

When importing mp4's containing dvcc box, MP4Box will fail complaining that:
`utils/bitstream.c:552:9: runtime error: shift exponent 4294967168 is too large for 32-bit type 'unsigned int'`
It was hapenning due to 160 being passed into the `gf_bs_write_int` (from dvcc_Write) and shifting the value beyond the valid range.
The fix ensures that the value is correctly written, by draining the count of bits all the way up until it reaches an acceptable value.

Fix shift exponent is too large in gf_bs_write_int

---

applications/mp4box/main.c
src/utils/os_config_init.c

[doing this as a PR to be sure we all agree with the change]
In order to get closer behavior between filters and master for MP4Box, this change makes `-p=0` (i.e.: don't use a config file on disk) the default **for MP4Box only** 
I also changed the meaning of `-p=` (empty string) to the previous default (i.e.: write GPAC.cfg in the default dir, not in profiles dir) (`-p=` (empty) used to be synonymous with `-p=0` but undocumented)

use -p=0 by default for MP4Box

---

Changelog

Copied the list of changes from https://github.com/gpac/gpac/releases/tag/v0.8.0
A current Changelog facilitates packaging. See #840
I do not think a new release is necessary based on this PR; this list of changes can just go on to become part of the Changelog for the upcoming 0.9.0 release.

Trivial: Update Changelog to 0.8.0

---

src/utils/alloc.c

hey all, 
doing this as a PR since it's just one possibility
currently when the mem tracker detects a leak it will dump the leaked object as a string, which will very probably include non printable characters
this poses some problems with terminals and also with our tests results interface (python refuses to display logs that are not proper utf-8)
the solution I chose here is to replace non-printable characters with dots and to add a hex dump
before: 
```
[MemTracker] Printing the current state of allocations (0 open file handles) :
[MemTracker] Memory Block 0x558f450779a0 (size 32) allocated in:
file isomedia/drm_sample.c at line 1130
string dump: 
avˈ
ȼf
[MemTracker] Memory Block 0x558f45077af0 (size 8) allocated in:
file isomedia/drm_sample.c at line 1139
string dump: [MemTracker] …
```

memtracker: add hex dump and remove unprintable chars

---

include/gpac/constants.h
include/gpac/internal/isomedia_dev.h
include/gpac/internal/media_dev.h
include/gpac/isomedia.h
include/gpac/mpeg4_odf.h
src/isomedia/avc_ext.c
src/isomedia/box_code_base.c
src/media_tools/av_parsers.c
src/media_tools/dash_segmenter.c
src/media_tools/media_import.c

DolbyVision support:
-  [X] RFC8361
-  [X] DASH (ok)
-  [X] Encryption (ok)
-  [ ] "Dolby recommends including a separate adaptation set that refers to an SDR version of the same content as the Dolby Vision stream." => filters only: put an "alt_codecs" on AS and force a  duplication in the MPD serializer by patchin the AS ID when serializing

Dolby vision

---

applications/mp4box/main.c
src/utils/constants.c

Fixes issues such as
```c
S:/media-autobuild_suite-master/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.1.0/../../../../i686-w64-mingw32/bin/ld.exe: ../../bin/gcc/libgpac_static.a(constants.o):constants.c:(.data+0x0): multiple definition of `itunes_tags'; main.o:main.c:(.bss+0x138): first defined here
```
Closes https://github.com/m-ab-s/media-autobuild_suite/issues/1762

itunes_tags: make the global variables static

---

src/utils/os_net.c

solves an issue with mingw-w64 clang that shows
```c
D:/ffmpeg-autobuild-clang/build/gpac-git/src/utils/os_net.c:950:9: error: use of undeclared identifier 'EPIPE'
case EPIPE:
^
D:/ffmpeg-autobuild-clang/build/gpac-git/src/utils/os_net.c:956:9: error: use of undeclared identifier 'EPROTOTYPE'
case EPROTOTYPE:
^
D:/ffmpeg-autobuild-clang/build/gpac-git/src/utils/os_net.c:959:9: error: use of undeclared identifier 'ENOBUFS'
case ENOBUFS:
^
3 errors generated.
```
Fixes https://github.com/m-ab-s/media-autobuild_suite/issues/1713
Signed-off-by: Christopher Degawa <ccom@randomderp.com>

src/utils/os_net.c: Include errno.h for windows

---

applications/mp4box/fileimport.c
src/Makefile
src/filter_core/filter_session.c
src/filters/bsrw.c
src/filters/compose.c
src/filters/dasher.c
src/filters/dec_bifs.c
src/filters/dec_odf.c
src/filters/dmx_gsf.c
src/filters/hevcmerge.c
src/filters/hevcsplit.c
src/filters/in_sock.c
src/filters/load_bt_xmt.c
src/filters/mux_gsf.c
src/filters/out_video.c
src/filters/reframe_nalu.c
src/filters/resample_audio.c
src/isomedia/iff.c
src/media_tools/isom_tools.c

Compiling at RHEL7 and configure some disable options, compile error has occurred.
The configure options are as follows:
```
./configure \
--strip \
--disable-ipv6 \
--disable-platinum \
--disable-alsa \
--disable-oss-audio \
--disable-jack \
--disable-pulseaudio \
--disable-x11 \
--disable-x11-shm \
--disable-x11-xv \
--disable-ssl \
--disable-3d \
--disable-svg \
--disable-vrml \
--disable-x3d \
--disable-odf \
--disable-bifs \
--disable-bifs-enc \
--disable-laser \
--disable-saf \
--disable-seng \
--disable-qtvr \
--disable-avi \
--disable-ogg \
--disable-dvb4linux \
--disable-swf \
--disable-scene-stats \
--disable-scene-dump \
--disable-scene-encode \
--disable-loader-isoff \
--disable-loader-bt \
--disable-loader-xmt \
--disable-od-dump \
--disable-crypt \
--disable-isoff-hds \ …
```

Disabled config

---

include/gpac/mpd.h
src/filters/dasher.c
src/media_tools/mpd.c

Based on DASH-IF IOP 4.3, section 3.2.9
Tested with: gpac -i input:FID=1 reframer:saps=1:FID=2 -o output.m3u8:dual:SID=1,2

DASH: add trick mode

---

applications/mp4box/main.c
configure
include/gpac/configuration.h
include/gpac/setup.h
src/export.cpp
src/utils/alloc.c

hi all, 
[ I'm doing this as a PR to keep a record of some info ]
**TL;DR:** I added `strlcpy` and we should probably use it instead of `str[n]cpy` in most cases
I had previously mentioned [here](https://github.com/gpac/gpac/issues/1474#issuecomment-728248865) that `str[n]cpy` causes some issues and that there are discussions about good alternatives.
To add to this, I'll paste an email I wrote elsewhere (in french, sorry) with more info : 
<hr />
* pour strncpy c'est toute une saga ...
En gros souvent quand on l'utilise ce qu'on veut qu'il fasse c'est :
1. copie ce que tu peux de source vers destination
2. si tu dois tronquer fais le
3. assure un \0 à la fin
Et strncpy ne fait pas ca. En particulier il ne garantis pas 3. Il ajoute aussi du padding inutile avec des 0 quand dest>src.  Et du …

added bsd strlcpy function for better string copies

---

include/gpac/internal/media_dev.h
src/media_tools/av_parsers.c

Corrects frame sizes for scalable images, among other applications.

AV1: Use sequence header resolution if frame override is not set.

---

include/gpac/internal/media_dev.h
src/filters/inspect.c
src/media_tools/av_parsers.c

Current MP4Box cannot parse multi-layered streams where the resolution and tiling changes. This fixes the bug.

fix parsing of layered AV1 streams with varying tile config

---

src/media_tools/img.c

On some JPEG files, the 0xFF + 0xC0/C1 markers could be contained before the actual start of frame. This may lead to inconsistency between the size extracted from rfimg filter and the one from imgdec (in my case it crashes the display).
This is a very small fix taken from this description :
http://vip.sugovica.hu/Sardi/kepnezo/JPEG%20File%20Layout%20and%20Format.htm
where Length should be equal "to 8 + components*3 value" in case it could be usefull to you.
Enclosed is a jpeg file to reproduce this error.

Verify JFIF markers before reading

---

.gitignore
Makefile
configure
debian/gpac.install
share/gpac.desktop

- install the application icon in the XDG hicolor icon theme, rather than the legacy pixmaps location
- make `gpac.desktop` file static, as it does not change anymore
- drop an extra key in `gpac.desktop`

Improve the desktop bits

---

src/utils/os_divers.c

fixed:
when parse '2021-07-31T12:50:20.000+08:00',
1)
(sscanf(val, "%d-%d-%dT%d:%d:%gZ", &year, &month, &day, &h, &m, &secs) == 6) is TRUE,
then oh = om = 0, 
should into 
(sscanf(val, "%d-%d-%dT%d:%d:%g+%d:%d", &year, &month, &day, &h, &m, &secs, &oh, &om) == 8)
2)
utc of '2021-07-31T12:50:20.000+08:00' is 2021-07-31 04:50:20,
so current_time should minus diff.

fix parse date

---

src/isomedia/avc_ext.c

This was probably a copy and paste error.

use correct type to allocate GF_VVCConfigurationBox

---

src/media_tools/av_parsers.c

I think there is a small bug in parsing AV1 streams with q matrices - see section 5.9.12 of the spec

AV1 parsing: only parse qm_v if sperarate_uv_delta_q is true

---

applications/mp4box/filedump.c
include/gpac/internal/media_dev.h
src/export.cpp
src/filters/inspect.c
src/isomedia/box_dump.c
src/isomedia/sample_descs.c
src/media_tools/av_parsers.c

This currently only works with `-dxml` and `-dnal`. I need to better understand the inspector architecture to add general inspection. 
Use it as follows:
1. encode some (multichannel) streams with `opusenc` (playing with `framesize` and `hard-cbr` produces different packet configurations):
```
opusenc --framesize 40 --hard-cbr FOA_music.wav FOA_music_framesize_40_hardcbr.opus 
opusenc --framesize 10 FOA_music.wav FOA_music_framesize_10.opus
...
```
2. Import to MP4 with FFmpeg:
```
ffmpeg -i file.opus -acodec copy file.mp4
```
3. Inspect with MP4Box
```
MP4Box -dxml file.mp4
```
You should see sample structures such as:
```
<Sample number="22" DTS="10080" CTS="10080" size="347" RAP="1" >
<OpusPacket offset="0" self_delimited="1" header_size="2" config="30" stereo="1" code="0" …
```

adding Opus packet inspection

---

src/isomedia/stbl_write.c

I noticed that when [merging tracks](https://github.com/gpac/gpac/blob/master/src/isomedia/track.c#L468), gpac gave up after 2^32 bytes.
Looks to me like a small bug in `stbl_AppendChunk`. One line got lost in the 64-bit codepath. The PR adds that line and now gpac works as expected when merging many tracks.

fix 64 bit chunk offsets when appending

---

src/filters/write_generic.c

XML <head> nodes are lost when extracting a TTML track from a fragmented MP4 to a single output file.
> MP4Box -raw 1 example.mp4
This PR adds merging of <head> nodes into the writegen process.
Hopefully all cases are covered.

Merge TTML <head> nodes during the writegen process

---

src/filters/write_generic.c

TTML extraction can crash if the first fragments contain no content or no <body> during the writegen process.
This PR fixes these 2 cases.

No content and no body case in TTML during the writegen process

---

include/gpac/setup.h
include/gpac/thread.h
src/utils/os_net.c

this is based on the article at http://wp.xin.at/archives/5810
see also previous discussion about xp support here: https://github.com/gpac/gpac/issues/1490#issuecomment-649519836
this allows building the "mp4box only" profile with xp compatible toolsets v140_xp or v141_xp
(it doesn't allow for a full build on xp, nor does it makes the official installers xp compatible)
tested with v140_xp on VS2015 and x141_xp on VS2019 on a xp sp3 x86 vm
<hr />
the added support for inet_ntop on xp might be overkill, we might just want to undefine GPAC_HAS_IPV6 on xp and not bother with the extra code, but it's debatable

add support for building mp4box on windows xp

---

include/gpac/internal/media_dev.h
src/filters/bsrw.c
src/media_tools/av_parsers.c

To generate a sample with vui timing info (and pic timing sei):
```
gpac -i avgen:dur=2 @ c=avc:r=30/1::x264-params="level=40:nal-hrd=vbr:vbv-bufsize=1000:vbv-maxrate=2000" @ -o avc30.mp4
```

Vui timing info rewrite

---

applications/gpac/gpac.c
applications/mp4box/filedump.c
include/gpac/avparse.h
include/gpac/constants.h
include/gpac/mpeg4_odf.h
src/export.cpp
src/filters/dasher.c
src/media_tools/av_parsers.c
src/utils/constants.c

`MP4Box -info file.eac3`
```
Import probing results for file.eac3:
File has 1 tracks
- Track 1 type: Audio - Codec Enhanced AC3 Audio
SampleRate 48000 - 6 channels
```
`MP4Box -add file.eac3 -new a.mp4`
```
Track Importing EAC-3 - SampleRate 48000 Num Channels 6
Saving a.mp4: 0.500 secs Interleaving0)
MP4Box -info a.mp4
Duration 00:00:04.223
Fragmented: no
Progressive (moov before mdat)
Major Brand isom - version 1 - compatible brands: isom
Created: GMT Tue Nov  1 23:45:23 2022
Meta-Data Tags:
tool: GPAC-2.1-DEV-rev431-g2db3785b3-eac3_cicp
Media Duration 00:00:04.224
Track flags: Enabled In Movie In Preview
Media Samples: 132
Alternate Group ID 1
Media Type: soun:ec-3
EC-3 stream - Sample Rate 48000 - 5.1 channel(s) - bitrate 192000
RFC6381 Codec Parameters: ec-3
All samples are sync
Max …
```

fix DASH channel layout configuration for EAC-3 streams with 6 channels

---

src/media_tools/isom_tools.c

A small change to fix writing out the VP9 codec level information to a.o. MPD files.

Again don't write vpcc->level as hex (#1114)

---

configure

Preserve user-specified linker flags on Darwin by appending library path instead of overwriting LDFLAGS.
Keeping user-specified flags is the behaviour on other platforms as well, so I assume that overwriting LDFLAGS was unintentional.
This change allows Macports insert its legacy-support library, so that gpac can be built on OS X versions without `clock_gettime` (i.e., 10.11 and earlier).

Configure: do not overwrite LDFLAGS on Darwin

---

share/scripts/jsf/uncvg.js

As written, it uses `x` without defining it, and it drops the final column digit since `slice(begin,end)` does not include `end`.
I'm not sure I completely understand the expected format, but assuming it is something like:
```
./bin/gcc/gpac uncvg:vsize=1000x2000:bpm=r300,r350,c200,c240,c280,100x120,130x150:fps=0 -o ~/uncompressed_sbpm.heif
```
then this PR should fix the parsing.
(also, I see the sbpm box included even if it is the bpm is not specified in the filter. Is that intended?)

uncvg: fix bad pixel map value parsing

---

src/media_tools/av_parsers.c

HEVC SPS parsing fails when sps_sub_layer_ordering_info _present_flag is set, and sps_max_sub_layers_minus1 is greater than 0. The result was three arrays weren’t being fully read.

Fix HEVC SPS parsing

---

src/filters/dasher.c

... to avoid duration being truncated (and last segment missing)

dasher: put default precision to ms (period_start.den=1000 instead of 1)

---

.gitignore
flake.lock
flake.nix

Hello,
This PR exists to add a nix flake in the repository to build GPAC (without the extra deps).
It integrates with https://nixos.org/ and allows you to build gpac (and get its dependencies) using ```ǹix build``` or just spawn an isolated development shell using ```nix develop```.
So far, only 64bit linux is supported, but mac and windows support could be enabled in the future. As well as 32bit linux.

Add nix flake to help builds with nix packages

---

applications/mp4box/fileimport.c

I was trying to use `colormx` overrides today using mp4box and it refused to be parsed on the commandline. I dug in and noticed that these string comparisons were checking the wrong lengths, so I figured I'd contribute the few I noticed to be wrong. There might be others hiding in there (this fixed my `colormx` usage, at least)!
While I'm at it, thanks for mp4box; it is great stuff.

Fix strnicmp lens on some fileimport comparisons

---

src/bifs/unquantize.c

fix #2567: integer overflow issue in bifs/unquantize.c:298

fix integer overflow issue in bifs/unquantize.c:298

---

src/utils/os_net.c

Fixing some bugs in netcap filtering:
- Accepting value `FF` when patching a byte in a packet
- Do not stop at the first netcap filtering rule

Fixing some bugs in netcap filtering

---

src/media_tools/route_dmx.c

Fix issue https://github.com/gpac/gpac/issues/2717
- Verifying that payload is not erroneously treated as plaintext => print warning message
- Checking if end of payload is reached
- When header entity is unrecognized, avoid printing whole payload
- Print error message if end of payload is reached prematurely

Fixing issue 2717

---

include/gpac/network.h
src/utils/os_net.c

Forcing the HOPS to zero when not specified is quite confusing to the user. We let the IPV4 implementation to default when TTL isn't specified, let's make IPV6 have the same behavior.

net: fix multicast IPV6 hops default value

---

share/emscripten/gpac.html

This is related to #2740. I've realized there were some problems with it. They are fixed by preventing default shortcuts on document level.

WASM demo page bug fixes

---

src/media_tools/route_dmx.c

- Corrected some typos.
- Fix: to prevent discarding future versions of the manifest if the first one is not correctly received.

Fix discarding manifests

---

src/media_tools/route_dmx.c
src/utils/xml_parser.c

- Check if start_offset doesn't go beyond total length `TOL`
- On error, set `last_dispatched_toi_on_tsi_zero` to 0
- purge object if total_length has changed (if object has not been received entirely)
- check exit code of `gf_route_service_setup_stsid` 
- On error after processing manifest, reset versions
- fix some bugs in xml parser
- infinite loop while looking for end of processing instruction
- check that manifest is entirely parsed

Buildbot somefixes

---

include/gpac/tools.h
src/media_tools/route_dmx.c
src/utils/error.c

-  Replace sscanf with strtol to ensure TOI field is parsed as an integer.
-  Replace sscanf with strtol to ensure TSI field is parsed as an integer.
-  Validate that the dport field is an integer within the range [0, 65535].
-  Verify if session channels are defined in the manifest.

Enhancements for Manifest Parsing and Validation

---

src/media_tools/route_dmx.c

When receiving LCT fragments, ensure that packets are not skipped if they overlap with received packets. 
This fix addresses the issue where skipping overlapped packets led to potential data loss or processing errors.

Fix: Do Not Skip Overlapping LCT Fragments

---

src/filters/dec_nvdec_sdk.c
src/filters/dec_nvdec_sdk.h

This fixes the following warnings:
```
...
filters/dec_nvdec.c: In function ‘nvdec_flush_frame’:
filters/dec_nvdec.c:1031:98: warning: passing argument 3 of ‘cuvidMapVideoFrame’ from incompatible pointer type [-Wincompatible-pointer-types]
1031 |                 res = cuvidMapVideoFrame(ctx->dec_inst->cu_decoder, f->frame_info.picture_index, &map_mem, &pitch, &params);
|                                                                                                  ^~~~~~~~
|                                                                                                  |
|                                                                                                  CUdeviceptr * {aka long long unsigned int *}
filters/dec_nvdec.c:1031:98: note: expected ‘unsigned int *’ but argument …
```

use correct pointer type for CUdeviceptr on aarch64 in nvdec filter

---

src/utils/gzio.c

This fixes build with zlib-ng, which doesn't define the macro.
Regardless, this macro was defined to memcpy in most cases anyway: https://github.com/madler/zlib/blob/master/zutil.h#L209

use plain memcpy instead of zmemcpy macro

---

src/filter_core/filter_pid.c
src/filters/in_route.c
src/isomedia/stbl_write.c
src/media_tools/route_dmx.c

- Fixing runtime error: 
> negation of -2147483648 cannot be represented in type 'int'
- Check if `filter` field is not null also to prevent segmentation fault
- In Route dmx, update `alloc_size` of an object if necessary when picking it from reservoir
- Cast to `u64` to avoid overflow in comparisons
- Purge segment if there are any fragments that extend beyond the total length
- Display warning message if received TOL is null

Fix bugs found by fuzzer

---

src/media_tools/route_dmx.c

Fix some autofuzz bugs:
- `nJauzoDhd5DctA`: skip packet when `start_offset + size > GF_UINT_MAX`  (Not supported)
- `yXRaBOYUxQRZFA`: null pointer passed as  second argument to `sscanf`

Error handling fixes

---

src/media_tools/mpd.c

This pull request addresses the issue of an infinite loop encountered when executing the specified command line.
- Download the capture file [route_nozip.zip](https://github.com/gpac/gpac/files/14836928/route_nozip.zip).
- Execute the following command line:
```
gpac -i route://234.1.1.1:1234/live.mpd -netcap=src=route_nozip.gpc,nrt,[s=1,o=847,v=40] inspect -logs=route@info
```
The command should execute without encountering an infinite loop.
**_Note_:** I am not sure if this is the correct approach to fix the issue, which is why I created this as a draft PR.

Fix infinite loop when segment_template is absent in MPD

---

configure

The configure test for xvid was failing to find it due to
```
*** CC/CXX Test Failed (res 1 args -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -arch x86_64 -L/opt/local/lib -lxvidcore -lpthread) : 
/opt/local/var/macports/build/_Volumes_Shared_macports-ports_multimedia_gpac/gpac/work/.tmp/gpac-conf-30001-60580-19987.c:2:70: error: use of undeclared identifier 'NULL'
int main( void ) { void *codec; xvid_decore(codec, XVID_DEC_DESTROY, NULL, NULL); return 0; }
^
/opt/local/var/macports/build/_Volumes_Shared_macports-ports_multimedia_gpac/gpac/work/.tmp/gpac-conf-30001-60580-19987.c:2:76: error: use of undeclared identifier 'NULL'
int main( void ) { void *codec; xvid_decore(codec, XVID_DEC_DESTROY, NULL, …
```

configure: Fix finding xvid by including stddef.h for definition of NULL

---

applications/gpac/gpac.c
src/filters/out_http.c

doing this as a PR for potential review
related to #2834
I made a patch to ignore the query string part of a url when looking for a file on disk
I've not done it for DELETE method and other scenarios 
one possible issue is that we're working on the url-decoded URI (without the %xx stuff), so if there was a url-encoded '?' character in the path it will be interpreted (wrongly) as the start of the query string (not sure if that would ever actually happen but just to keep in mind)

httpout server: ignore query strings when getting file on disk (#2834)

---

src/media_tools/route_dmx.c

This PR addresses the error message `pthread_mutex_destroy failed with error code 16` during the repair process.
**Changes:**
- In the function `routedmx_check_blob_range`, unlock mutex `blob->mx` before returning.

Fix `pthread_mutex_destroy failed` issue during repair process

---

src/filters/inspect.c

See context at
https://github.com/AOMediaCodec/libavif/pull/2182
Temporal Delimiter OBU headers are 2 bytes long.

Do not skip TD OBU in gf_inspect_dump_obu

---

src/isomedia/isom_read.c

Fix runtime error: member access within null pointer
Add check on `movie->moov` variable
autofuzz bug DmhCZI7TfPXPxQ

fix: runtime error member access within null pointer

---

applications/mp4box/filedump.c
applications/mp4box/fileimport.c

This fixes:
```
filedump.c:64:14: warning: type of ‘swf_flatten_angle’ does not match original declaration [-Wlto-type-mismatch]
64 | extern Float swf_flatten_angle;
|              ^
mp4box.c:217:89: note: type ‘Double’ should match type ‘Float’
217 | Double interleaving_time, split_duration, split_start, dash_duration, dash_subduration, swf_flatten_angle, mpd_live_duration, min_bu
ffer, mpd_update_time;
|                                                                                         ^
mp4box.c:217:89: note: ‘swf_flatten_angle’ was previously declared here
mp4box.c:217:89: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
```
and
```
fileimport.c:110:14: warning: type of ‘swf_flatten_angle’ does not match original declaration [-Wlto-type-mismatch]
110 | extern …
```

correct `swf_flatten_angle` type

---

src/media_tools/route_dmx.c

check null pointer before calling `strcmp`
autofuzz bug FWTEsQ5kS498yw

fix bug null pointer when calling strcmp

---

src/isomedia/media.c

fix `double-free`, `bad-free`, and `heap-use-after-free` issues
autofuzz bug `hh4LjpASSgbe5w`; `m9ncfi-rO16uCA`; `2du1EHRvDJl0Xw`; `EO-JJdpd4pGtwA`

fix: double-free, bad-free, and heap-use-after-free issues

---

share/emscripten/gpac.html

fixes #2856 - Import directory in WASM demo is broken
In the [WASM console](https://wasm.gpac.io), when importing a directory using the `imp -d [NAME]` command, the imported files were always created relative to the root directory, instead of being created relative to the current directory. 
This PR implements the current directory as the default import destination when NAME  is undefined, otherwise it checks if NAME is an absolute or relative path and behaves accordingly.

fix imp -d relative to current directory

---

src/filters/ff_enc.c

As part of #2879 I've discovered that if `GF_PROP_PCK_CUE_START` was present in a packet, encoder would go in a reconfiguration loop

Preventing FFmpeg encoder from unnecessary reconfiguring

---

src/filters/dasher.c

Found with @DenizUgur when investigating why prft boxes were absent from segment with 'ntp=yes'

dasher: only remove ntp when explicitely asked

---

src/media_tools/mpd.c

As indicated by [CR-Low-Latency-Live-r8.pdf](https://dashif.org/docs/CR-Low-Latency-Live-r8.pdf) 9.X.4.5.5 `availabilityTimeComplete` must be present and be set to `false`

Add `availabilityTimeComplete` to SegmentTemplate

---

include/gpac/filters.h
src/export.cpp
src/filter_core/filter_props.c

`filters.h` already includes the definition. Having this function available would be great for applications using libgpac and pass PID properties via string.

export `gf_props_parse_value`

---

src/quickjs/quickjs-libc.c

gcc 14 promoted -Wincompatible-pointer-types to an error and now shows
```c
src/quickjs/quickjs-libc.c:3376:49: error: passing argument 2 of 'GetExitCodeProcess' from incompatible pointer type [-Wincompatible-pointer-types]
3376 |                 GetExitCodeProcess(pi.hProcess, &ret);
|                                                 ^~~~
|                                                 |
|                                                 int *
```

quickjs-libc: fix incompatible pointer error with gcc 14

---

include/gpac/internal/media_dev.h
src/filters/reframe_nalu.c
src/media_tools/av_parsers.c

- A fix for the parsing of the SPS is provided. This is because for NALUs associated with layers whose identifier is greater than 0 the spec requires the decoder to parse sps_ext_or_max_sub_layers_minus1 (see F.7.3.2.2.1). The value of this syntax element is then used to infer the value for sps_max_sub_layers_minus1 as specified in Clause F.7.4.3.2.1. The current design would led to have sps_max_sub_layers_minus1 equal to zero. This is fine for streams captured by devices such as Apple iPhones since the value for sps_ext_or_max_sub_layers_minus1 is set to 7 and the spec in this case mandates that sps_max_sub_layers_minus1 assumes the same value transmitted in the SPS. However, different encoders might be setting sps_ext_or_max_sub_layers_minus1 to a different value, thus also …

Support for the Multiview extension of H.265/HEVC

---

src/filters/mux_isom.c

`prft` box is useful outside dashing as well. It allows precise timing information for custom protocols.

Add prft box outside dashing

---

src/filters/out_route.c

DVB mabr: Adding an option to offer the possibility of selecting how the manifests and init
segments are delivered:
- either in the multicast gateway configuration transport session .
- or in the multicast transport sessions delivering the content.

Buildbot mabr inband mani init transport

---

src/isomedia/box_dump.c

While checking some uncompressed files, I noted that the ComponentInfo values seemed off.
Possibly left over from when the number of components field (`nb_comps`) expanded from 16 to 32 bits.

uncompressed: fix ComponentInfo dump

---

include/gpac/internal/isomedia_dev.h
src/isomedia/box_code_base.c
src/isomedia/box_dump.c
src/isomedia/box_funcs.c

closes #2919
**Adds:**
- `jp2p`
- `jsub`
- `orfo`
- `jP  ` (added dump definitions)

Motion JPEG 2000 Boxes

---

src/filters/inspect.c
src/filters/isoffin_load.c
src/filters/load_text.c
src/filters/reframe_av1.c
src/filters/reframe_flac.c
src/filters/reframe_latm.c
src/filters/reframe_nalu.c
src/filters/reframe_qcp.c
src/filters/reframe_rawvid.c
src/isomedia/isom_write.c
src/media_tools/dash_client.c
src/media_tools/mpeg2_ps.c
src/scene_manager/swf_parse.c
src/utils/xml_parser.c

Hi all,
For clarity and record keeping, I'm putting all of these in a single PR, with each bug in its own commit. 
Thanks and credits to @skorpion98 and @Heinzeen from Sapienza University of Rome for the detection and responsible disclosure of these issues. 
I don't think any of these poses great security concerns since the path to exploitation seems really difficult. 
However we've had functional seemingly-random bugs caused by uninitialized variables before, so these reports are valuable to remove some sources of undefined behavior. 
Sorry in advance if the recommendations in this section seem trivial or obvious, but the existence of these issues show that we need to be more vigilant on a few points: 
When using local variables in a block, remember to give them an initial value (0/-1 …

fix a bunch of use-of-uninitialized-memory errors

---

src/filters/reframer.c

Opened in place of #2950
By placing a reframer with `:sapcue=3`, we signal that the dasher may use this information to define segment boundaries. The value given to `sapcue` will determine which SAPs get treated as cues. SAPs smaller than or equal to a given value will signal cues. However, for that to happen dasher must be configured to use in-band cues via `:cues=inband`

Treat SAPs as Cue Points

---

src/filters/write_generic.c
src/filters/write_vtt.c

Add the ability to export the WebVTT track when no cues are present in the track.
```
MP4Box -raw <vtt_track_id> --noempty=0 test.mp4
gpac -i test.mp4 @#text -o test.vtt:!noempty
```

Write empty WebVTT file if no cue is present

---

src/filters/inspect.c

Example of wrong SCTE marker:
https://tools.middleman.tv/scte35-parser?hex=FC302F00000000000000FFF00506FE19206BBE0019021743554549000000057FC0000052636200016134000000009B016FB3&format=json

fix for invalid file that use non-zero upid length even if the upid type is not set

---

applications/gpac/gpac_help.c
src/utils/os_config_init.c

This PR addresses two minor issues related to documentation printing:
- The `</div>` tag is now printed only if `gen_doc==1` to avoid unnecessary HTML tags in cases where documentation generation is not required.
- Replaced spaces with tabs for consistent formatting across the codebase.

Fix doc printing and formatting issues: Conditionally print </div>

---

applications/gpac/gpac_help.c

This PR introduces a new feature that allows users to print all available options for a specific filter using the `gpac -h <filtername>.*` or `gpac -h <filtername>.@`

Add support for displaying all filter options using filtername.* or filtername.@ syntax

---

src/filter_core/filter_props.c

Added bullet points (`- `) to the help output for a more convenient and consistent presentation of options.

chore: enhance help output for "gpac -h props" with bullet points

---

.gitignore

This PR updates the `.gitignore` file to exclude Python cache files. The following entries were added:
- `__pycache__/`: to ignore Python bytecode directories.
- `*.py[cod]`: to ignore compiled Python files.

Update .gitignore to exclude Python cache files

---

applications/gpac/gpac_help.c

This PR addresses an issue where the `gpac -ha protocols` and `gpac -hh protocols` commands displayed the list of input and output filters for each protocol incorrectly, with input filters shown under "out" and output filters under "in". The filter lists are now correctly categorized and displayed.

Fix inverted display of input/output filters in protocols  help

---

src/filters/ff_dmx.c

`avdevice_list_input_sources` was added back in libavcodec 56, we use this function in gpac only if libavcodec is 58 or greater.
Closes #2991

Fix build issues for FFmpeg 7+

---

modules/dx_hw/dx_window.c
src/compositor/events.c
src/compositor/svg_font.c
src/filters/load_text.c
src/filters/write_tx3g.c
src/isomedia/box_dump.c
src/isomedia/isom_write.c
src/scene_manager/scene_dump.c

```
unsigned short utf16Line = gf_malloc( sizeof(u16)  s_txt->len);
[...]
len = gf_utf8_mbstowcs((u16*)utf16Line, 10000, (const char **) &str);
```
We have this hardcoded pattern. It seems safe because the underlying buffer sizes shouldn't allow to go beyond the allocated size. However this is weird. Does anyone remember how we ended up with this in the code?

UTF conversion buffer sizes: fix crash in .ts -> ccdec -> .vtt conversion

---

src/filters/compose.c

This PR fixes the documentation for the `epow2` property in the compositor filter. The documentation incorrectly used `yes/no` instead of `true/false` to describe the boolean values. This change corrects the documentation to use `true/false` for consistency and clarity.
- Updated the description of the `epow2` property to use `true/false` instead of `yes/no`.

Fix documentation for 'epow2' property in compositor filter to use 'true/false' instead of 'yes/no'

---

src/filters/in_route_repair.c

This PR improves the repair session logic to ensure that the repair process does not abandon byte range repairs after blacklisting a server that does not support byte range requests. Instead, it will attempt to use an alternative server if available.

Do Not Abandon Repairing Byte Range After Blacklisting a Repair Server

---

applications/gpac/gpac_help.c

This PR improves the `parse_sep_set` function by adding robust validation and logging mechanisms. The following changes have been made:
- **Separator Set Length Check:** Added checks to ensure the separator set length does not exceed the allowed size.
- **Logging Enhancements:** Implemented logging for cases where the separator set is too long or truncated.
- **Duplicate Character Validation:** Added validation to detect and log duplicate characters in the separator set.
- **Reversion Mechanism:** Reverted to the previous separator set if duplicates are found to maintain consistency.
These enhancements aim to improve the reliability and maintainability of the `parse_sep_set` function by ensuring that invalid separator sets are properly handled and logged.

Enhance parse_sep_set Function with Validation and Logging

---

src/filter_core/filter.c

This PR addresses the issue where multiple enum values with the same name were causing ambiguity in filter arguments. The changes ensure that such cases are handled correctly by logging appropriate warnings and ignoring ambiguous arguments.
- Added new variables to track counts and save specific arguments.
- Adjusted the logic in `filter_parse_dyn_args` function to handle ambiguous arguments and log warnings.
- Updated relevant parts of the code to ensure correct handling of enum values.
This PR fixes the issue of ambiguous enum values in filter arguments.

Handle Multiple Enum Values with Same Name in Filter Arguments

---

src/filters/bsrw.c
src/filters/dec_nvdec.c
src/filters/dmx_dash.c
src/filters/in_http.c
src/filters/mux_isom.c
src/filters/mux_ts.c
src/filters/out_video.c
src/filters/write_nhml.c

This PR includes the following changes to improve type safety and consistency:
- fix type of `bsrw.vidfmt`: `GF_PROP_SINT` instead of `GF_PROP_UINT`.
- Declare all `enum` arguments as `u32` variables to maintain consistency and prevent type mismatches.
PS: This PR is a follow-up to the closed PR #2984

Ensure Enum Arguments are of u32 Type

---

configure

These options in the build were setting the has_jack, has_pulseaudio or has_alsa variables respectively.
However, their values were being later replaced inside the check_has_lib() function, resulting in those options not affecting the enable status of those libraries in anyway.
This patch fixes it by disabling these features with the disabled_packages list, as done for other features.

Fix --disable-jack, --disable-pulseaudio, --disable-alsa

---

src/filters/in_route.c
src/media_tools/dash_client.c
src/utils/downloader.c

The original issue can be reproduced:
```
gpac -i https://livesim2.dashif.org/livesim2/segtimeline_1/testpic_2s/Manifest.mpd dashin:forward=file -o mabr://234.1.1.1:1234 -logs=route@warning -ifce=127.0.0.1 -no-h2
```
and client that will stop playing by lack of seg timeline update:
```
gpac -i mabr://234.1.1.1:1234:repair=no vout -ifce=127.0.0.1
```

dash client: increase stl tolerance when being ahead of time from 1 seg to 1.5 seg dur

---

include/gpac/filters.h
share/python/libgpac/libgpac.py
src/export.cpp
src/filter_core/filter_pid.c
src/utils/constants.c

- **get the filter owning the pid**: If you only have access to the PID you don't have a way to get the owning filter, the new API adds that ability.
- **search stream type by their short name**: This is for easily understanding the stream type just by using the first part of MIME.

API Additions for Filter and Constants

---

src/filters/write_vtt.c

Related to #2962, changed the default behaviour of `write_vtt` to export the WebVTT file even there are no cues present. Testsuite has also been updated to test this change.

Change default behavior of `noempty`

---

include/gpac/internal/isomedia_dev.h
src/isomedia/box_code_base.c

This adds version 1 support for the CompositionToDecodeBox (`cslg`) as described in ISO/IEC 14496-12:2022 Section 8.6.1.4.
This is used by the GStreamer rust muxer, and is not properly parsed. Instead, there is a command line warning about 20 extra bytes.

isomedia: implement cslg version 1

---

src/filters/inspect.c
src/filters/reframer.c

- **fix: improve timestamp comparison logic in reframer filter**
- **feat: add timecode formatting in inspect output**

Timecode formatting in `inspect`

---

src/filters/in_route_repair.c

- Changed a variable type from `u32` to `Bool` as it logically acts as a boolean.
- Updated initialization of a `u32` variable from `GF_FALSE` to `0` for better readability and coherence with the codebase.

Refactored variable types and initialization for clarity and consistency.

---

include/gpac/filters.h

Probably a harmless change, this change could help override an element with a custom one without explicit linking. Since the priority is a `u8` now, it's not possible to go below 0 without `s16`

Make Filter Priority Signed

---

src/isomedia/box_dump.c

When dumping a mp4 file with DTS boxes, using `-diso` the resulting `_info.xml` file has invalid XML syntax. Report from `xmllint`:
```text
-:32: parser error : attributes construct error
RepresentationType="4" ChannelLayout="15" MultiAssetFlag="0" LBRDurationMod="0"
^
-:32: parser error : Couldn't find end of Start Tag DTSpecificBox line 32
RepresentationType="4" ChannelLayout="15" MultiAssetFlag="0" LBRDurationMod="0"
^
-:32: parser error : Opening and ending tag mismatch: AudioSampleDescriptionBox line 31 and DTSSpecificBox
ype="4" ChannelLayout="15" MultiAssetFlag="0" LBRDurationMod="0"</DTSSpecificBox
^
```
There are two problems:
* The opening element name is misspelled `DTSpecificBox`, which should be `DTSSpecificBox`
* The element is not properly terminated with a `>` character

ddts_box_dump: fix start element name, ensure attributs end with '>'

---

include/gpac/internal/media_dev.h
src/filters/bsrw.c
src/filters/reframe_nalu.c
src/media_tools/av_parsers.c

This PR adds a new option called `seis` to `bsrw`. The new option would allow filtering SEIs rather than removing them all or not (see `rmsei`)
Testsuite PR: https://github.com/gpac/testsuite/pull/24 https://github.com/gpac/testsuite/pull/25

Ability to Filter SEIs

---

src/isomedia/isom_write.c
src/isomedia/meta.c

From the HEIF specification (ISO/IEC 14496-12:2022), Section 8.11.14.1:
> Each ItemPropertyAssociationBox shall be ordered by increasing item_ID, and there shall
> be at most one occurrence of a given item_ID, in the set of ItemPropertyAssociationBox
> boxes.

Make sure that `impa` boxes are sorted by item id

---

.github/workflows/abi-version.yml

The new workflow is designed to help us track the ABI version across commits. The procedure is as follows:  
1. Whenever a push occurs, build both the current commit and the latest `abi-*` tag.  
2. Check if the ABI has changed. If so, determine whether it is a minor or major change.  
3. Update or create the tags to point to the current commit: `abi-<major>.<minor>` and `abi-<major>`.  
4. Open a PR that updates the ABI version inside the code and includes the output of `abipkgdiff` in the PR body.  
**Notes:**  
- In case of staggered pushes, the workflow will be queued and processed atomically.  
- Whenever a new ABI change is pushed, the PR will be updated.  
> [!WARNING]  
> Since we are updating the `abi-*` tags, you must run `git pull --tags -f` to update your local tags.  
> …

New workflow to update ABI version automatically

---

src/filters/inspect.c

add support for dumping unregistered SEI with timecode extraction

---

include/gpac/internal/media_dev.h
include/gpac/tools.h
src/filters/bsrw.c
src/filters/inspect.c
src/filters/rewrite_obu.c
src/media_tools/av_parsers.c
src/utils/constants.c

Add time_code (136) SEI to HEVC/AVC. And equivalent for AV1.
- **force reframer when working with timecodes**
- **move `tc` from `ufobu` to `bsrw` and support removing of tc**

`bsrw` timecode manipulation

---

applications/gpac/gpac_help.c
include/gpac/constants.h
src/filters/ff_dmx.c
src/filters/ff_mx.c
src/filters/mux_isom.c

This PR introduces a new `proto` flag to the FFmpeg's [muxer](https://wiki.gpac.io/Filters/ffmx/) and [demuxer](https://wiki.gpac.io/Filters/ffdmx/) filters. The idea is to leverage FFmpeg's protocols (srt://, rtmp://, ... that are also visible in `gpac -h protocols`) while not using the corresponding muxer (resp. MPEG-TS, FLV, ...). This is useful if you want to pass a content that FFmpeg can't remux (or demux) properly.
Example forwarding some MPEG-TS over SRT (`reframer:rt=on` adds realtime regulation):
- Using GPAC's muxer: `gpac -i file.ts reframer:rt=on -o srt://127.0.0.1:9999\?mode=listener:gpac:proto` 
- By-passing all muxers: `gpac -i file.ts:block_size=1880 reframer:rt=on -o srt://127.0.0.1:9999\?mode=caller:gpac:proto`
You can also do fancy stuff such as putting some mp4 or …

ffmx: forwarding to protocol without remuxing

---

src/filters/dasher.c

This allows dasher to derive first segment number from cts
Example:
```bash
gpac avgen:v:dur=8:fps=10 c=avc:bf=0:fintra=2 reframer:xs=4:xots -o out.mpd:segdur=2:segcts
```
In this example, only 3rd and 4th segments should be created.

new `segcts` option to derive startNumber from cts

---

src/filters/bsrw.c
src/filters/sei_load.c
src/media_tools/av_parsers.c

refactored `bsrw` to use `seiload` but encountered bad_access errors from`seiload`.
Added HEVC/AV1 tests to the testsuite so that we can ensure everything is working as required. These hashes were generated with an earlier commit before #3169 was merged.
- gpac/testsuite/pull/30

`seiload` issues

---

src/filters/reframer.c

This PR brings support for using timecodes when `xs` is set to a XML DateTime. Timecodes within media stream are converted to UTC using current UTC date. If the given `xs` value is out-of-bounds for the media stream, then CTS of the packets will reflect that difference. As if the video was playing since `xs` but packets just started to arrive.
Assume that current UTC time is `2025-04-16T12:16:06Z` (time is not important) and our media stream starts at `14:00:00:00` timecode. The video is running at `60fps`. For simplicity sake there is only video in this example but other streams going through `reframer` will be adjusted so that they follow along the video.
We instruct the reframer to split from `2025-04-16T13:00:00Z` and since timecodes start 1 hour after that time the first CTS will be …

make utc_ref work with timecodes

---

src/media_tools/av_parsers.c

- Fixes unexpected timescales and possible AV sync issues in IAMF-FLAC.
- Sample rate is 20 bytes in section 8.1 of RFC 9639.
- The coded sample size is offset by 1.

Fix IAMF-FLAC sample size and sample rate.

---

.github/workflows/abi-version.yml
.github/workflows/updatewiki.yml

Hi all, 
This is linked to https://github.com/gpac/wiki/issues/7
This PR contains a github actions that does the following on a push to master: 
- waits for the new docker image to be built and uploaded
- uses this docker image as a container with latest gpac
- clones the wiki in this container
- runs the genmd.sh script from the wiki
- commits and pushes to the wiki if there are changes
You can see an example run with changes here: https://github.com/aureliendavid/gpac/actions/runs/14863298639/job/41733595309
Leading to this commit: https://github.com/aureliendavid/wiki/commit/2c3bde6be461cbff2762874f7025dbf3952b5a14
And an example of run with no change here: https://github.com/aureliendavid/gpac/actions/runs/14863341530/job/41733749576
Note that I have not checked the genmd.sh script …

Github Actions: Update wiki on gpac push

---

include/gpac/internal/isomedia_dev.h
src/isomedia/box_dump.c
src/isomedia/box_funcs.c
src/isomedia/iff.c

This adds support for the item properties in ISO/IEC 23008-12:2025 Section 6.10 "Text and font items", which was recently published.
There are three properties - `txlo`, `elng` and `fnch`. `elng` is borrowed from 14496-12, and the implementation in this PR does the same. 
I could not find sample data that matches the spec. There is a sample at https://github.com/MPEGGroup/FileFormatConformance/pull/133/files#diff-1bddd1e6a414e35db8bedca0a507c50e4b8288a72b33dd19e67860d4bf8df0be that is close, but the `txlo` appears to be from an earlier iteration - there is is no `writing_mode` string, and the `width` and `height` values look a bit strange.
The XML dump from gpac with this PR against that sample looks (in part) like this:
```
<ItemPropertyContainerBox Size="270" Type="ipco" …
```

iff: add text and font properties
